### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by pombredanne** [jboss-eap/maven-repository-builder#111]
Hi! What would be the license for this fine utility? I cannot find one in the repo.

**Comment by pkocandr** [comment]
Hi! Thanks for pointing this out.
@pgier @dosoudil @VaclavDedik @janinko Any preference? I think ASL 2.0 would be fine. But TBH I'm not experienced in picking a license.

**Comment by janinko** [comment]
TBH I don't care, anything you chose I'm fine. I know we were using Apache License on some projects.
Some info can be found here: http://choosealicense.com/

**Comment by VaclavDedik** [comment]
I also don't really care, Apache Licence 2.0 or MIT is ok with me.

**Comment by sgilda** [comment]
Not sure if it's useful, but the quickstarts and archetypes use this license (the year needs updating): https://github.com/jboss-developer/maven-qstools-plugin/blob/master/config/default/license.txt

**Comment by pombredanne** [comment]
Thank you all for chiming in: any license would work

**Comment by pombredanne** [comment]
And then the doc is pushed as part of the build to https://readthedocs.org/

**Comment by pgier** [comment]
I'm OK with whatever we pick.  I'd probably go with the Apache license that sgilda linked

**Comment by pombredanne** [comment]
@pkocandr Thank you.
